runtime: nodejs8
service: appteststandard
env_variables:
  SQL_USER: 'root'
  SQL_PASSWORD: 'password123'
  SQL_DATABASE: 'parkingDatabase'
  INSTANCE_CONNECTION_NAME: 'intro2cloudcomputing18:us-west1:parking-sql-instance'
  NODE_ENV: 'production'
beta_settings:
    # The connection name of your instance, available by using
    # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
    # the Instance details page in the Google Cloud Platform Console.
    cloud_sql_instances: 'intro2cloudcomputing18:us-west1:parking-sql-instance'