runtime: nodejs
service: apptest
env: flex
env_variables:
  SQL_USER: 'root'
  SQL_PASSWORD: 'password123'
  SQL_DATABASE: 'parkingDatabase'

beta_settings:
# The connection name of your instance, available by using
# 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
# the Instance details page in the Google Cloud Platform Console.
cloud_sql_instances: 'intro2cloudcomputing18:us-west1:parking-sql-instance'